In [55]:
import numpy as np
a = np.array([[ 1, 2, 3, 3, 1],[6, 8, 11, 10, 7]]).T
a


array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [56]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

In [57]:
a_centered = a-mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [60]:
a_centered_sp = a_centered[:,0]@a_centered[:,1]
a_centered_sp

8.0

In [66]:
b =a_centered_sp/(len(a_centered)-1)

b

2.0

In [70]:
import pandas as pd

In [71]:
author_name = ['Тургенев', 'Чехов', 'Островский']

In [69]:
author_id = [1,2,3]

In [90]:
authors = pd.DataFrame({"author_id":[1, 2, 3],'author_name':['Тургенев', 'Чехов', 'Островский']})   
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [104]:
book = pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3], 'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'], 'price':[450, 300, 350, 500, 450, 370, 290]})
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

In [105]:
?pd.merge()

Object `pd.merge()` not found.


In [108]:
authors_price = pd.merge(authors, book, on = 'author_id',how = 'inner')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [133]:
top5 = authors_price.nlargest(5, "price")
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

In [142]:
authors_stat_1 = authors_price.groupby('author_name')
a = authors_stat_1["price"].max()
b = authors_stat_1["price"].min()
c = authors_stat_1["price"].mean()
authors_stat = pd.DataFrame({ 'min_price':b,'max_price':a, 'mean_price' :c})

authors_stat

min_price  max_price  mean_price
author_name                                  
Островский         290        370  330.000000
Тургенев           300        450  366.666667
Чехов              450        500  475.000000